### ISSUE TITLE
View and edit packed files

### ISSUE THREAD

**Issue by JJL772** [momentum-mod/lumper#27]
It'd be nice to have the ability to view, add and remove files packed into the BSP. Right now this can only be done using the `bspzip` command line tool. I was considering writing a Qt tool in-engine to do this, however lumper seems like a better fit for such a thing (plus it's open source!)

**Comment by tsa96** [comment]
`feat/pakfileUI`, BIRD's current WIP branch seems to be working on this. Though yeah, we didn't actually really have an issue for this. So, it's coming!

**Comment by JJL772** [comment]
Just saw the PR, good stuff!
