### ISSUE TITLE
Saving can produce corrupted static prop lumps

### ISSUE THREAD

**Issue by tsa96** [momentum-mod/lumper#38]
This appears to be happening in even on the staticpropsv13 branch, before any of my refactors, and I haven't found a fix yet.

Static props won't load in-game, and trying to load the outputted BSP will throw.

Loading and saving various official Momentum maps works atm, e.g. sj_rapunzel.

**Comment by BIRD311** [comment]
should work now feat/staticpropV13

**Comment by tsa96** [comment]
Nice! IDK how I didn't notice that, great to have fixed though. Will mark closed when my PR comes in, which includes your fixes.
