### ISSUE TITLE
Unable to load BSP - Funny staticprop length

### ISSUE THREAD

**Issue by Mac-tf2** [momentum-mod/lumper#46]
Trying to load ahop_orange throws the error ``InvalidDataException: Funny staticprop length (14440 != 13680)``

**Comment by dbampersand** [comment]
Three more files that break: https://filebin.net/wf75sz124bnxnthp

There's an int division in @tsa96 's fix for this that fails to trigger in some cases that needs to be fixed: 

Change 
```c#
            if (remainingLength / StaticProps.StructureSize != entries)
```

To: 
```c#
            if (MathF.Ceiling(remainingLength / (float) StaticProps.StructureSize) != entries)
```

**Comment by tsa96** [comment]
Why's the ceil needed, don't we want to fail if the structure size is not a factor of remaining length? Might be misremembering the details of this

**Comment by dbampersand** [comment]
Actually, yeah - the ceil is a bad way to do this. Something like this is better:

```c#
            if (remainingLength / StaticProps.StructureSize != entries || remainingLength % StaticProps.StructureSize != 0)
```

**Comment by tsa96** [comment]
Isn't `remainingLength % StaticProps.StructureSize != 0` always true if `remainingLength / StaticProps.StructureSize != entries` is true, given that `entries` is an integer? Second guessing myself now, but if `A / B` is a integer, then `A % B == 0`, right?

I haven't had a chance to test the maps you posted yet, could you explain why current check fails? Can probably figure it out from the values of `remainingLength`, `StaticProps.StructureSize` and `entries`. When I was working on this, I found debugging and setting a breakpoint after the check failed very helpful.

**Comment by dbampersand** [comment]
When loading jump_above:

```
remainingLength = 144
StaticProps.StructureSize = 68
entries = 2
```

144/68 = ~2.12 so it rounds to 2 which doesn't pass remainingLength / StaticProps.StructureSize != entries and so it never gets set to V7s.

**Comment by tsa96** [comment]
So if `StaticProps.StructureSize` is 68, it's trying to fit a V8, and according to remaining length it's a V9 (144/2 = 72 which corresponds to V9).

I don't know the how the stupid prop versioning works, or why the current code only tries to fit V10s into V7s specifically, perhaps we should be doing that between other versions? @BIRD311 might be able to clarify

**Comment by dbampersand** [comment]
It enters into the function as a V7 (also 68 bytes) but it's actually a V7s.

```C#
public override int StructureSize => ActualVersion switch {
        StaticPropVersion.V4 => 56,
        StaticPropVersion.V5 => 60,
        StaticPropVersion.V6 => 64,
        StaticPropVersion.V7 => 68,
        StaticPropVersion.V7s => 72,
        StaticPropVersion.V8 => 68,
        StaticPropVersion.V9 => 72,
        StaticPropVersion.V10 => 76,
        StaticPropVersion.V11 => 80,
        StaticPropVersion.V12 => 80,
        StaticPropVersion.V13 => 88,
        _ => 1
    };
```

**Comment by tsa96** [comment]
Oh woops, thought structuresize was unique to each version and didn't notice the other ones!

Just tried this out, you're right about it being an integer division, it's just that we want to still the comparison using floats. Just pushed a fix, seems to work for the maps you provided.
